// Code generated by gobee. DO NOT EDIT.
// source: testdata/golden/helloworld.go

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

char _license[] SEC("license") = "GPL";

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__type(key, __u32);
	__type(value, __u64);
	__uint(max_entries, 1);
} PktCount SEC(".maps");

SEC("xdp")
int CountPackets(struct xdp_md *ctx) {
	__u32 key = 0;
	__u64 *count = bpf_map_lookup_elem(&PktCount, &key);
	if (!count) {
		return XDP_PASS;
	}
	__sync_fetch_and_add(count, 1);
	return XDP_PASS;
}
