package transpile

import (
	"fmt"
	"go/printer"
	"io"
	"sort"
	"strings"
)

// WriteBindings emits a Go file with typed accessors for the program's
// BPF programs and maps. Consumers use cilium/ebpf's LoadAndAssign
// machinery via the generated `Load<Stem>` helper, replacing the
// stringly-typed `coll.Programs["X"]` / `coll.Maps["Y"]` lookups with
// `objs.X` / `objs.Y` field access.
//
// sourcemap is the bytes of the corresponding `.bpf.c.map` file. It is
// embedded as a raw Go string in the generated file so `Load<Stem>` can
// annotate any *ebpf.VerifierError returned by LoadAndAssign with Go
// source positions, without depending on the .map file being shipped
// alongside the binary at runtime.
func WriteBindings(w io.Writer, prog *Program, packageName, stem string, sourcemap []byte) error {
	if packageName == "" {
		return fmt.Errorf("WriteBindings: empty package name")
	}
	if stem == "" {
		return fmt.Errorf("WriteBindings: empty stem")
	}
	pascal := pascalCase(stem)

	progFields := make([]bindingField, 0, len(prog.Programs))
	for _, p := range prog.Programs {
		progFields = append(progFields, bindingField{
			Go:      pascalCase(p.Name),
			ELF:     p.Name,
			Section: p.Section,
		})
	}
	sort.Slice(progFields, func(i, j int) bool { return progFields[i].Go < progFields[j].Go })

	attachers := make([]attachHelper, 0, len(progFields))
	for _, f := range progFields {
		a := attachFor(f.Section)
		if a == nil {
			continue
		}
		a.Field = f
		attachers = append(attachers, *a)
	}
	needsLink := len(attachers) > 0

	mapFields := make([]bindingField, 0, len(prog.Maps))
	for _, m := range prog.Maps {
		mapFields = append(mapFields, bindingField{Go: pascalCase(m.Name), ELF: m.Name})
	}
	sort.Slice(mapFields, func(i, j int) bool { return mapFields[i].Go < mapFields[j].Go })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gobee. DO NOT EDIT.\n//\n")
	fmt.Fprintf(&b, "// Typed accessors for the BPF programs and maps declared in %s.\n", stem+".go")
	fmt.Fprintf(&b, "// Use Load%s with a *ebpf.CollectionSpec to populate this struct;\n", pascal)
	fmt.Fprintf(&b, "// access programs and maps via objs.<Name> instead of\n")
	fmt.Fprintf(&b, "// coll.Programs[\"<name>\"] / coll.Maps[\"<name>\"].\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"errors\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/cilium/ebpf\"\n")
	if needsLink {
		b.WriteString("\t\"github.com/cilium/ebpf/link\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\tbpfvetanalyzer \"github.com/boratanrikulu/bpfvet/pkg/analyzer\"\n")
	b.WriteString("\tbpfvetversion \"github.com/boratanrikulu/bpfvet/pkg/version\"\n")
	b.WriteString("\t\"golang.org/x/sys/unix\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/boratanrikulu/gobee/diagnose\"\n")
	b.WriteString(")\n\n")

	// Programs struct
	fmt.Fprintf(&b, "// %sPrograms holds one *ebpf.Program per //bpf:section function.\n", pascal)
	fmt.Fprintf(&b, "type %sPrograms struct {\n", pascal)
	for _, f := range progFields {
		fmt.Fprintf(&b, "\t%s *ebpf.Program `ebpf:%q`\n", f.Go, f.ELF)
	}
	b.WriteString("}\n\n")

	// Maps struct
	fmt.Fprintf(&b, "// %sMaps holds one *ebpf.Map per package-level map declaration.\n", pascal)
	fmt.Fprintf(&b, "type %sMaps struct {\n", pascal)
	for _, f := range mapFields {
		fmt.Fprintf(&b, "\t%s *ebpf.Map `ebpf:%q`\n", f.Go, f.ELF)
	}
	b.WriteString("}\n\n")

	// Objects struct (programs + maps)
	fmt.Fprintf(&b, "// %sObjects bundles every program and map for one transpilation unit.\n", pascal)
	fmt.Fprintf(&b, "type %sObjects struct {\n", pascal)
	fmt.Fprintf(&b, "\t%sPrograms\n", pascal)
	fmt.Fprintf(&b, "\t%sMaps\n", pascal)
	b.WriteString("}\n\n")

	// Close method
	fmt.Fprintf(&b, "// Close releases every map and program owned by o.\n")
	fmt.Fprintf(&b, "func (o *%sObjects) Close() error {\n", pascal)
	b.WriteString("\tvar errs []error\n")
	for _, f := range mapFields {
		fmt.Fprintf(&b, "\tif o.%s != nil { errs = append(errs, o.%s.Close()) }\n", f.Go, f.Go)
	}
	for _, f := range progFields {
		fmt.Fprintf(&b, "\tif o.%s != nil { errs = append(errs, o.%s.Close()) }\n", f.Go, f.Go)
	}
	b.WriteString("\treturn errors.Join(errs...)\n}\n\n")

	// Loader function. Before LoadAndAssign:
	//   - bpfvet portability analyzer refuses to load when the running
	//     kernel is older than the spec needs (avoids the cryptic "invalid
	//     argument" from old kernels missing required helpers).
	// After LoadAndAssign:
	//   - if the kernel returned a *ebpf.VerifierError, the embedded
	//     sourcemap rewrites every "<stem>.bpf.c:N" reference in the log
	//     to "<go-file>:<line>:<col>" so the user sees a Go-source error
	//     instead of a raw C-line dump.
	fmt.Fprintf(&b, "// Load%s populates a fresh %sObjects from spec. Before loading the\n", pascal, pascal)
	fmt.Fprintf(&b, "// program into the kernel, it asks bpfvet what kernel version the\n")
	fmt.Fprintf(&b, "// spec needs and compares against the running kernel. After loading,\n")
	fmt.Fprintf(&b, "// any *ebpf.VerifierError is annotated with Go source positions from\n")
	fmt.Fprintf(&b, "// the embedded sourcemap.\n")
	fmt.Fprintf(&b, "func Load%s(spec *ebpf.CollectionSpec) (*%sObjects, error) {\n", pascal, pascal)
	fmt.Fprintf(&b, "\tif err := check%sKernel(spec); err != nil {\n", pascal)
	fmt.Fprintf(&b, "\t\treturn nil, err\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tobjs := &%sObjects{}\n", pascal)
	b.WriteString("\tif err := spec.LoadAndAssign(objs, nil); err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn nil, annotate%sVerifierErr(err)\n", pascal)
	b.WriteString("\t}\n")
	b.WriteString("\treturn objs, nil\n}\n\n")

	// Embedded sourcemap + verifier-error annotator. Per-stem to support
	// multiple bindings in one package.
	fmt.Fprintf(&b, "// %sSourceMap is the C-line → Go-position table for %s.bpf.c. It's\n", pascal, stem)
	fmt.Fprintf(&b, "// embedded so Load%s can annotate verifier errors without shipping\n", pascal)
	fmt.Fprintf(&b, "// the .map file alongside the binary.\n")
	fmt.Fprintf(&b, "var %sSourceMap = `%s`\n\n", pascal, string(sourcemap))

	fmt.Fprintf(&b, "// annotate%sVerifierErr wraps err. If err is a *ebpf.VerifierError,\n", pascal)
	fmt.Fprintf(&b, "// every C-line reference in the verifier log is annotated with the\n")
	fmt.Fprintf(&b, "// matching Go source position. Other errors pass through unchanged.\n")
	fmt.Fprintf(&b, "func annotate%sVerifierErr(err error) error {\n", pascal)
	b.WriteString("\tvar verr *ebpf.VerifierError\n")
	b.WriteString("\tif !errors.As(err, &verr) {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\tsm, perr := diagnose.ParseSourceMapBytes([]byte(%sSourceMap))\n", pascal)
	b.WriteString("\tif perr != nil {\n")
	b.WriteString("\t\treturn err // sourcemap parse failed; keep the original error\n")
	b.WriteString("\t}\n")
	b.WriteString("\tannotated := diagnose.AnnotateLines(verr.Log, sm)\n")
	b.WriteString("\treturn fmt.Errorf(\"%w\\n\\n----- annotated verifier log -----\\n%s\", err, strings.Join(annotated, \"\\n\"))\n")
	b.WriteString("}\n")

	// Per-stem kernel check helper — analyzer + uname comparison. Stem
	// prefix avoids collision when multiple bindings live in one package.
	fmt.Fprintf(&b, "func check%sKernel(spec *ebpf.CollectionSpec) error {\n", pascal)
	b.WriteString("\trep, err := bpfvetanalyzer.AnalyzeSpec(spec)\n")
	b.WriteString("\tif err != nil || rep == nil {\n")
	b.WriteString("\t\treturn nil // can't analyze; fall through to LoadAndAssign for a real error\n")
	b.WriteString("\t}\n")
	b.WriteString("\trunning, ok := runningKernel()\n")
	b.WriteString("\tif !ok || !running.Less(rep.MinKernel) {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn fmt.Errorf(\"bpf program needs kernel >= %s, host is %s\", rep.MinKernel, running)\n")
	b.WriteString("}\n")

	// Attach helpers — one per program, derived from its //bpf:section
	// directive. Eliminates the userspace boilerplate of stating the same
	// tracepoint category/name/symbol that the kernel-side code already
	// declared.
	for _, a := range attachers {
		b.WriteString("\n")
		fmt.Fprintf(&b, "// Attach%s %s\n", a.Field.Go, a.Doc)
		fmt.Fprintf(&b, "func (o *%sObjects) Attach%s(%s) (link.Link, error) {\n", pascal, a.Field.Go, a.Params)
		fmt.Fprintf(&b, "\treturn %s\n", strings.Replace(a.Body, "$PROG", "o."+a.Field.Go, 1))
		b.WriteString("}\n")
	}

	// AttachAll: one call attaches every program whose section gobee
	// understands. XDP programs need an ifindex; pass 0 to skip them.
	if len(attachers) > 0 {
		hasXDP := false
		for _, a := range attachers {
			if a.Field.Section == "xdp" {
				hasXDP = true
				break
			}
		}
		b.WriteString("\n")
		fmt.Fprintf(&b, "// AttachAll attaches every program whose //bpf:section gobee\n")
		fmt.Fprintf(&b, "// understands. The returned slice is in declaration order; on\n")
		fmt.Fprintf(&b, "// error any links already opened are closed before returning.\n")
		if hasXDP {
			fmt.Fprintf(&b, "// xdpIfindex is the network interface index for XDP programs;\n")
			fmt.Fprintf(&b, "// pass 0 to skip XDP attachment.\n")
			fmt.Fprintf(&b, "func (o *%sObjects) AttachAll(xdpIfindex int) ([]link.Link, error) {\n", pascal)
		} else {
			fmt.Fprintf(&b, "func (o *%sObjects) AttachAll() ([]link.Link, error) {\n", pascal)
		}
		fmt.Fprintf(&b, "\tvar ls []link.Link\n")
		fmt.Fprintf(&b, "\tcleanup := func() { for _, l := range ls { l.Close() } }\n")
		for _, a := range attachers {
			switch a.Field.Section {
			case "xdp":
				fmt.Fprintf(&b, "\tif xdpIfindex != 0 {\n")
				fmt.Fprintf(&b, "\t\tl, err := o.Attach%s(xdpIfindex)\n", a.Field.Go)
				fmt.Fprintf(&b, "\t\tif err != nil { cleanup(); return nil, fmt.Errorf(\"attach %s: %%w\", err) }\n", a.Field.Go)
				fmt.Fprintf(&b, "\t\tls = append(ls, l)\n")
				fmt.Fprintf(&b, "\t}\n")
			default:
				fmt.Fprintf(&b, "\tif l, err := o.Attach%s(); err != nil {\n", a.Field.Go)
				fmt.Fprintf(&b, "\t\tcleanup(); return nil, fmt.Errorf(\"attach %s: %%w\", err)\n", a.Field.Go)
				fmt.Fprintf(&b, "\t} else { ls = append(ls, l) }\n")
			}
		}
		fmt.Fprintf(&b, "\treturn ls, nil\n}\n")
	}

	// runningKernel: shared, package-level helper. The kernel-version probe
	// in every Load<Stem> calls into it. Emitted once per stem; if a single
	// package gets multiple stems (rare) the duplicate definitions will
	// fight — accept that limitation rather than splitting bindings into
	// two files.
	b.WriteString("\n")
	b.WriteString("// runningKernel parses /proc/sys/kernel/osrelease via uname(2) and\n")
	b.WriteString("// returns the host's kernel as a bpfvet KernelVersion. Returns\n")
	b.WriteString("// ok=false on any parse failure so callers fall through to the\n")
	b.WriteString("// regular load path.\n")
	b.WriteString("func runningKernel() (bpfvetversion.KernelVersion, bool) {\n")
	b.WriteString("\tvar u unix.Utsname\n")
	b.WriteString("\tif err := unix.Uname(&u); err != nil {\n")
	b.WriteString("\t\treturn bpfvetversion.KernelVersion{}, false\n")
	b.WriteString("\t}\n")
	b.WriteString("\trelease := unix.ByteSliceToString(u.Release[:])\n")
	b.WriteString("\tvar major, minor int\n")
	b.WriteString("\tif _, err := fmt.Sscanf(release, \"%d.%d\", &major, &minor); err != nil {\n")
	b.WriteString("\t\treturn bpfvetversion.KernelVersion{}, false\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn bpfvetversion.V(major, minor), true\n")
	b.WriteString("}\n\n")

	// Re-publish user-defined struct types (verbatim, names already public).
	if len(prog.Types) > 0 {
		b.WriteString("\n// User-defined types from the kernel-side program. Layout matches\n")
		b.WriteString("// the kernel struct so encoding/binary on the userspace side and\n")
		b.WriteString("// clang's struct layout in the kernel agree byte-for-byte.\n\n")
		for _, t := range prog.Types {
			b.WriteString("type ")
			if err := printer.Fprint(&b, prog.FileSet, t.Spec); err != nil {
				return fmt.Errorf("print type %s: %w", t.Name, err)
			}
			b.WriteString("\n\n")
		}
	}

	// Re-publish user-defined consts with capitalized names so userspace
	// can reference the same values the kernel uses.
	if len(prog.Consts) > 0 {
		b.WriteString("// Constants mirrored from the kernel-side program. Capitalized so\n")
		b.WriteString("// userspace can reference them directly (kernel-side names may be\n")
		b.WriteString("// unexported; the bindings always export them).\n")
		b.WriteString("const (\n")
		for _, c := range prog.Consts {
			fmt.Fprintf(&b, "\t%s = ", pascalCase(c.Name))
			if err := printer.Fprint(&b, prog.FileSet, c.Value); err != nil {
				return fmt.Errorf("print const %s: %w", c.Name, err)
			}
			b.WriteString("\n")
		}
		b.WriteString(")\n")
	}

	_, err := io.WriteString(w, b.String())
	return err
}


type bindingField struct {
	Go      string // identifier in the generated Go struct
	ELF     string // exact map/program name in the .bpf.o ELF
	Section string // raw //bpf:section directive value
}

// attachHelper describes one generated Attach<Name> method. Body uses
// the literal placeholder $PROG which is replaced with `o.<Field>` at
// emit time so the body strings can stay short and readable.
type attachHelper struct {
	Field  bindingField
	Doc    string // sentence-completing the prefixed "// Attach<Name> "
	Params string // method parameter list, possibly empty
	Body   string // the `link.X(...)` expression body, with $PROG placeholder
}

// attachFor maps a //bpf:section value to an attach-helper template, or
// returns nil if gobee doesn't yet know how to attach this program kind
// from the bindings layer (the user can still attach manually via
// objs.<Name>).
func attachFor(section string) *attachHelper {
	switch {
	case section == "xdp":
		return &attachHelper{
			Doc:    "attaches the XDP program to the network interface with the given index.",
			Params: "ifindex int",
			Body:   "link.AttachXDP(link.XDPOptions{Program: $PROG, Interface: ifindex})",
		}
	case strings.HasPrefix(section, "tracepoint/"):
		// tracepoint/<category>/<name>
		parts := strings.SplitN(strings.TrimPrefix(section, "tracepoint/"), "/", 2)
		if len(parts) != 2 {
			return nil
		}
		return &attachHelper{
			Doc:    fmt.Sprintf("attaches the tracepoint %s/%s.", parts[0], parts[1]),
			Params: "",
			Body:   fmt.Sprintf("link.Tracepoint(%q, %q, $PROG, nil)", parts[0], parts[1]),
		}
	case strings.HasPrefix(section, "kprobe/"):
		symbol := strings.TrimPrefix(section, "kprobe/")
		return &attachHelper{
			Doc:    fmt.Sprintf("attaches the kprobe to %s.", symbol),
			Params: "",
			Body:   fmt.Sprintf("link.Kprobe(%q, $PROG, nil)", symbol),
		}
	case strings.HasPrefix(section, "kretprobe/"):
		symbol := strings.TrimPrefix(section, "kretprobe/")
		return &attachHelper{
			Doc:    fmt.Sprintf("attaches the kretprobe to %s.", symbol),
			Params: "",
			Body:   fmt.Sprintf("link.Kretprobe(%q, $PROG, nil)", symbol),
		}
	}
	return nil
}

// pascalCase upper-cases the first rune. Internal-only helper for
// translating ELF symbol names like `events` or `OnExec` into Go field
// names like `Events` and `OnExec`.
func pascalCase(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 'a' - 'A'
	}
	return string(r)
}
