package transpile

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"strings"
)

// Emit produces the BPF C source for a parsed program along with a
// sourcemap that lets `gobee diagnose` map verifier errors back to the
// originating Go source positions. sourceLabel is the path or label
// written into the "source:" header comment.
//
// Programs that read kernel-struct fields get the CO-RE header set
// (vmlinux.h + bpf_core_read.h); programs that don't get the lighter
// <linux/bpf.h> include and don't need a vmlinux.h vendored next to
// them. The choice is automatic.
func Emit(prog *Program, sourceLabel string) ([]byte, []SourceMapping, error) {
	e := &emitter{
		prog:    prog,
		buf:     &bytes.Buffer{},
		cLine:   1,
		aliases: make(map[types.Object]string),
	}
	e.writeHeader(sourceLabel, usesKernelFieldAccess(prog))
	e.writeLicense()
	for _, name := range usedPreludeHelpers(prog) {
		e.writeRaw(bpfPreludeHelpers[name])
		e.writeln("")
	}
	for _, t := range prog.Types {
		if err := e.writeUserType(t); err != nil {
			return nil, nil, err
		}
	}
	for _, m := range prog.Maps {
		if err := e.writeMap(m); err != nil {
			return nil, nil, err
		}
	}
	for _, h := range prog.Helpers {
		if err := e.writeHelper(h); err != nil {
			return nil, nil, err
		}
	}
	for _, p := range prog.Programs {
		if err := e.writeProgram(p); err != nil {
			return nil, nil, err
		}
	}
	return e.buf.Bytes(), e.mappings, nil
}

type emitter struct {
	prog     *Program
	buf      *bytes.Buffer
	indent   int
	cLine    int             // current line in the emitted C, 1-based
	mappings []SourceMapping // populated as statements are emitted
	aliases  map[types.Object]string
}

func (e *emitter) writef(format string, args ...any) {
	s := fmt.Sprintf(format, args...)
	e.cLine += strings.Count(s, "\n")
	e.buf.WriteString(s)
}

func (e *emitter) writeln(s string) {
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
	e.cLine++
}

func (e *emitter) writeIndent() { e.buf.WriteString(strings.Repeat("\t", e.indent)) }

// writeRaw emits s verbatim, tracking newlines for the sourcemap. Used
// for static helper bodies pulled from the prelude.
func (e *emitter) writeRaw(s string) {
	e.cLine += strings.Count(s, "\n")
	e.buf.WriteString(s)
}

// recordPos pairs the current C line with a Go source position. Called at the
// top of each emit step (statement, map decl, program header, license) so
// the sourcemap covers every meaningful chunk of output.
func (e *emitter) recordPos(pos token.Pos) {
	if !pos.IsValid() {
		return
	}
	e.mappings = append(e.mappings, SourceMapping{
		CLine:    e.cLine,
		Position: e.prog.FileSet.Position(pos),
	})
}

// declString joins a C type and a variable name with libbpf-style spacing:
// pointer types attach the `*` to the variable (`struct xdp_md *ctx`).
func declString(cType, name string) string {
	if strings.HasSuffix(cType, "*") {
		return cType + name
	}
	return cType + " " + name
}

func (e *emitter) writeHeader(source string, withCoRE bool) {
	e.writeln("// Code generated by gobee. DO NOT EDIT.")
	e.writef("// source: %s\n\n", source)
	if withCoRE {
		// Programs that read kernel struct fields use vmlinux.h plus
		// bpf_core_read.h so the field reads get BTF-relocated at load
		// time. The user vendors vmlinux.h next to their .bpf.c.
		e.writeln(`#include "vmlinux.h"`)
		e.writeln("#include <bpf/bpf_helpers.h>")
		e.writeln("#include <bpf/bpf_core_read.h>")
	} else {
		// Programs that only call helpers and return constants don't
		// need vmlinux.h. The static UAPI header is enough.
		e.writeln("#include <linux/bpf.h>")
		e.writeln("#include <bpf/bpf_helpers.h>")
	}
	e.writeln("")
}

// usesKernelFieldAccess reports whether the emitted C needs the CO-RE
// header set (vmlinux.h + bpf_core_read.h). True when:
//   - any //bpf:section function takes a kernel-typed context that's only
//     defined in vmlinux.h (e.g. SyscallEnterCtx), or
//   - any function body reaches into a kernel-context struct field
//     (e.g. ctx.IngressIfIndex on *bpf.XdpMd).
func usesKernelFieldAccess(prog *Program) bool {
	for _, p := range prog.Programs {
		if p.Decl.Type.Params != nil {
			for _, field := range p.Decl.Type.Params.List {
				if requiresVmlinuxParam(prog, field.Type) {
					return true
				}
			}
		}
		if p.Decl.Body == nil {
			continue
		}
		var found bool
		ast.Inspect(p.Decl.Body, func(n ast.Node) bool {
			if found {
				return false
			}
			sel, ok := n.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			t := prog.Info.TypeOf(sel.X)
			if t == nil {
				return true
			}
			if ptr, ok := t.(*types.Pointer); ok {
				t = ptr.Elem()
			}
			named, ok := t.(*types.Named)
			if !ok {
				return true
			}
			if isKernelContextStruct(named) {
				found = true
				return false
			}
			return true
		})
		if found {
			return true
		}
	}
	return false
}

// usedPreludeHelpers returns the names of bpf-package sugar functions
// (in deterministic order) used anywhere in the program that require a
// static C helper to be emitted at the top of the .bpf.c.
func usedPreludeHelpers(prog *Program) []string {
	seen := map[string]bool{}
	var out []string
	for _, p := range prog.Programs {
		if p.Decl.Body == nil {
			continue
		}
		ast.Inspect(p.Decl.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			id, ok := sel.X.(*ast.Ident)
			if !ok {
				return true
			}
			obj := prog.Info.Uses[id]
			if obj == nil {
				return true
			}
			pkgName, ok := obj.(*types.PkgName)
			if !ok || pkgName.Imported().Path() != bpfPkgPath {
				return true
			}
			if _, has := bpfPreludeHelpers[sel.Sel.Name]; has && !seen[sel.Sel.Name] {
				seen[sel.Sel.Name] = true
				out = append(out, sel.Sel.Name)
			}
			return true
		})
	}
	return out
}

// requiresVmlinuxParam reports whether a function parameter's type points
// to a bpf-package struct that needs vmlinux.h to compile.
func requiresVmlinuxParam(prog *Program, expr ast.Expr) bool {
	t := prog.Info.TypeOf(expr)
	if t == nil {
		return false
	}
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}
	info, ok := bpfPackageTypeInfo(named)
	return ok && info.needsVmlinux
}

func (e *emitter) writeLicense() {
	e.writef("char _license[] SEC(\"license\") = %q;\n\n", e.prog.License)
}

func (e *emitter) writeUserType(t *UserTypeDecl) error {
	e.recordPos(t.Spec.Pos())
	st, ok := t.Type.Underlying().(*types.Struct)
	if !ok {
		return fmt.Errorf("%s: user type %s must be a struct", t.Pos, t.Name)
	}
	e.writef("struct %s {\n", t.Name)
	e.indent++
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		e.writeIndent()
		// Fixed arrays render as `T name[N]` in C, not `T[N] name`.
		if arr, ok := f.Type().(*types.Array); ok {
			elemC, err := goTypeToC(arr.Elem())
			if err != nil {
				return fmt.Errorf("%s: field %s: %w", t.Pos, f.Name(), err)
			}
			e.writef("%s %s[%d];\n", elemC, f.Name(), arr.Len())
			continue
		}
		ftype, err := goTypeToC(f.Type())
		if err != nil {
			return fmt.Errorf("%s: field %s: %w", t.Pos, f.Name(), err)
		}
		e.writef("%s;\n", declString(ftype, f.Name()))
	}
	e.indent--
	e.writeln("};")
	e.writeln("")
	return nil
}

func (e *emitter) writeMap(m *MapDecl) error {
	if m.Spec != nil {
		e.recordPos(m.Spec.Pos())
	}
	cType, ok := mapTypeToC[m.Type]
	if !ok {
		return fmt.Errorf("%s: unsupported map type %q", m.Pos, m.Type)
	}
	e.writeln("struct {")
	e.writef("\t__uint(type, %s);\n", cType)

	// Different map shapes use different __type lines:
	//   ringbuf                       : type only
	//   queue/stack/bloom_filter      : type + value (no key)
	//   prog_array, perf_event_array  : hardcoded uint32/uint32 (kernel ABI)
	//   default                       : type + key + value
	switch m.Type {
	case "ringbuf":
		// no key, no value
	case "queue", "stack", "bloom_filter":
		if m.ValType == nil {
			return fmt.Errorf("%s: map type %q requires a value type argument", m.Pos, m.Type)
		}
		valC, err := goTypeToC(m.ValType)
		if err != nil {
			return fmt.Errorf("%s: map value: %w", m.Pos, err)
		}
		e.writef("\t__type(value, %s);\n", valC)
	case "prog_array", "perf_event_array":
		e.writeln("\t__type(key, __u32);")
		e.writeln("\t__type(value, __u32);")
	case "devmap", "xskmap":
		// Userspace populates each slot with an ifindex (devmap) or an
		// AF_XDP socket fd (xskmap). Both are __u32 from the verifier's
		// perspective — the Go-side type carries no V parameter.
		e.writeln("\t__type(key, __u32);")
		e.writeln("\t__type(value, __u32);")
	case "cpumap":
		// cpumap entries are `struct bpf_cpumap_val` (a __u32 qsize plus
		// an optional follow-up program fd). Userspace fills it in;
		// kernel-side just calls Redirect.
		e.writeln("\t__type(key, __u32);")
		e.writeln("\t__type(value, struct bpf_cpumap_val);")
	case "task_storage", "sk_storage", "inode_storage":
		// Per-object storage maps: kernel-sized (no max_entries),
		// require BPF_F_NO_PREALLOC, key is always `int` (libbpf ABI).
		if m.ValType == nil {
			return fmt.Errorf("%s: map type %q requires a value type argument", m.Pos, m.Type)
		}
		valC, err := goTypeToC(m.ValType)
		if err != nil {
			return fmt.Errorf("%s: map value: %w", m.Pos, err)
		}
		e.writeln("\t__uint(map_flags, BPF_F_NO_PREALLOC);")
		e.writeln("\t__type(key, int);")
		e.writef("\t__type(value, %s);\n", valC)
		e.writef("} %s SEC(\".maps\");\n\n", m.Name)
		return nil
	default:
		if m.KeyType == nil {
			return fmt.Errorf("%s: map type %q requires key and value type arguments", m.Pos, m.Type)
		}
		keyC, err := goTypeToC(m.KeyType)
		if err != nil {
			return fmt.Errorf("%s: map key: %w", m.Pos, err)
		}
		valC, err := goTypeToC(m.ValType)
		if err != nil {
			return fmt.Errorf("%s: map value: %w", m.Pos, err)
		}
		e.writef("\t__type(key, %s);\n", keyC)
		e.writef("\t__type(value, %s);\n", valC)
	}
	e.writef("\t__uint(max_entries, %d);\n", m.MaxEntries)
	e.writef("} %s SEC(\".maps\");\n\n", m.Name)
	return nil
}

// writeHelper emits a user-defined Go helper as a C function with
// `static __always_inline` linkage so the BPF verifier inlines it into
// every caller (BPF doesn't support indirect calls in most program
// types and global functions need a separate `int` return convention
// — inlining keeps the verifier happy without exposing those rules to
// the user).
func (e *emitter) writeHelper(h *HelperFunc) error {
	e.recordPos(h.Decl.Pos())
	fd := h.Decl

	retC := "void"
	if fd.Type.Results != nil {
		switch len(fd.Type.Results.List) {
		case 0:
			// no-op
		case 1:
			r := fd.Type.Results.List[0]
			if len(r.Names) > 1 {
				return fmt.Errorf("%s: %s: multiple return values are not supported", h.Pos, h.Name)
			}
			rt := e.prog.Info.TypeOf(r.Type)
			c, err := goTypeToC(rt)
			if err != nil {
				return fmt.Errorf("%s: %s return: %w", h.Pos, h.Name, err)
			}
			retC = c
		default:
			return fmt.Errorf("%s: %s: multiple return values are not supported", h.Pos, h.Name)
		}
	}

	var params []string
	if fd.Type.Params != nil {
		for _, field := range fd.Type.Params.List {
			pt := e.prog.Info.TypeOf(field.Type)
			pc, err := goTypeToC(pt)
			if err != nil {
				return fmt.Errorf("%s: %s param: %w", h.Pos, h.Name, err)
			}
			if len(field.Names) == 0 {
				params = append(params, pc)
				continue
			}
			for _, n := range field.Names {
				params = append(params, declString(pc, n.Name))
			}
		}
	}
	paramList := "void"
	if len(params) > 0 {
		paramList = strings.Join(params, ", ")
	}

	e.writef("static __always_inline %s %s(%s) {\n", retC, h.Name, paramList)
	e.indent++
	if err := e.writeBlock(fd.Body); err != nil {
		return err
	}
	e.indent--
	e.writeln("}")
	e.writeln("")
	return nil
}

func (e *emitter) writeProgram(p *ProgramFunc) error {
	e.recordPos(p.Decl.Pos())
	e.writef("SEC(%q)\n", p.Section)

	// Emit signature: int Name(struct xdp_md *ctx) for XDP.
	fd := p.Decl
	if fd.Type.Params == nil || len(fd.Type.Params.List) != 1 {
		return fmt.Errorf("%s: %s: expected exactly one parameter", p.Pos, p.Name)
	}
	param := fd.Type.Params.List[0]
	if len(param.Names) != 1 {
		return fmt.Errorf("%s: %s: expected single named parameter", p.Pos, p.Name)
	}
	paramName := param.Names[0].Name
	paramType := e.prog.Info.TypeOf(param.Type)
	paramC, err := goTypeToC(paramType)
	if err != nil {
		return fmt.Errorf("%s: %s param: %w", p.Pos, p.Name, err)
	}

	e.writef("int %s(%s) {\n", p.Name, declString(paramC, paramName))
	e.indent++
	if err := e.writeBlock(fd.Body); err != nil {
		return err
	}
	e.indent--
	e.writeln("}")
	return nil
}

func (e *emitter) writeBlock(b *ast.BlockStmt) error {
	for _, stmt := range b.List {
		if err := e.writeStmt(stmt); err != nil {
			return err
		}
	}
	return nil
}

func (e *emitter) writeStmt(stmt ast.Stmt) error {
	e.recordPos(stmt.Pos())
	switch s := stmt.(type) {
	case *ast.DeclStmt:
		return e.writeDeclStmt(s)
	case *ast.AssignStmt:
		return e.writeAssignStmt(s)
	case *ast.IfStmt:
		return e.writeIfStmt(s)
	case *ast.ReturnStmt:
		return e.writeReturnStmt(s)
	case *ast.ExprStmt:
		return e.writeExprStmt(s)
	case *ast.ForStmt:
		return e.writeForStmt(s)
	case *ast.BlockStmt:
		e.writeIndent()
		e.writeln("{")
		e.indent++
		if err := e.writeBlock(s); err != nil {
			return err
		}
		e.indent--
		e.writeIndent()
		e.writeln("}")
		return nil
	case *ast.IncDecStmt:
		e.writeIndent()
		expr, err := e.formatExpr(s.X)
		if err != nil {
			return err
		}
		op := "++"
		if s.Tok == token.DEC {
			op = "--"
		}
		e.writef("%s%s;\n", expr, op)
		return nil
	}
	return fmt.Errorf("%s: unsupported statement type %T", e.prog.FileSet.Position(stmt.Pos()), stmt)
}

func (e *emitter) writeDeclStmt(ds *ast.DeclStmt) error {
	gd, ok := ds.Decl.(*ast.GenDecl)
	if !ok || gd.Tok != token.VAR {
		return fmt.Errorf("%s: only var decls are supported in function bodies", e.prog.FileSet.Position(ds.Pos()))
	}
	for _, spec := range gd.Specs {
		vs := spec.(*ast.ValueSpec)
		for i, name := range vs.Names {
			t := e.prog.Info.TypeOf(name)
			cType, err := goTypeToC(t)
			if err != nil {
				return fmt.Errorf("%s: %w", e.prog.FileSet.Position(name.Pos()), err)
			}
			e.writeIndent()
			if vs.Values != nil && i < len(vs.Values) {
				val, err := e.formatExpr(vs.Values[i])
				if err != nil {
					return err
				}
				e.writef("%s = %s;\n", declString(cType, name.Name), val)
			} else {
				e.writef("%s;\n", declString(cType, name.Name))
			}
		}
	}
	return nil
}

func (e *emitter) writeAssignStmt(as *ast.AssignStmt) error {
	// Special case: `count, ok := PktCount.Lookup(&key)` (comma-ok on map lookup).
	if as.Tok == token.DEFINE && len(as.Lhs) == 2 && len(as.Rhs) == 1 {
		if call, ok := as.Rhs[0].(*ast.CallExpr); ok {
			if mapName, valType, isLookup := e.mapLookupCall(call); isLookup {
				return e.writeMapLookup(as, call, mapName, valType)
			}
			if mapName, valType, isReserve := e.ringbufReserveCall(call); isReserve {
				return e.writeRingbufReserve(as, mapName, valType)
			}
			if mapName, valType, helper, isGet := e.storageGetCall(call); isGet {
				return e.writeStorageGet(as, call, mapName, valType, helper)
			}
		}
		return fmt.Errorf("%s: only map Lookup, RingBuf Reserve, or storage Get may be used with comma-ok", e.prog.FileSet.Position(as.Pos()))
	}

	if len(as.Lhs) != 1 || len(as.Rhs) != 1 {
		return fmt.Errorf("%s: multi-value assignment not supported", e.prog.FileSet.Position(as.Pos()))
	}
	lhs, err := e.formatExpr(as.Lhs[0])
	if err != nil {
		return err
	}
	rhs, err := e.formatExpr(as.Rhs[0])
	if err != nil {
		return err
	}
	e.writeIndent()
	switch as.Tok {
	case token.DEFINE:
		// `x := expr` → emit with inferred type.
		id, ok := as.Lhs[0].(*ast.Ident)
		if !ok {
			return fmt.Errorf("%s: := requires an identifier on the left", e.prog.FileSet.Position(as.Pos()))
		}
		t := e.prog.Info.TypeOf(id)
		cType, err := goTypeToC(t)
		if err != nil {
			return err
		}
		e.writef("%s = %s;\n", declString(cType, id.Name), rhs)
	case token.ASSIGN:
		e.writef("%s = %s;\n", lhs, rhs)
	case token.ADD_ASSIGN, token.SUB_ASSIGN, token.MUL_ASSIGN, token.QUO_ASSIGN, token.REM_ASSIGN,
		token.AND_ASSIGN, token.OR_ASSIGN, token.XOR_ASSIGN, token.SHL_ASSIGN, token.SHR_ASSIGN:
		e.writef("%s %s %s;\n", lhs, as.Tok.String(), rhs)
	default:
		return fmt.Errorf("%s: unsupported assignment %q", e.prog.FileSet.Position(as.Pos()), as.Tok)
	}
	return nil
}

func (e *emitter) writeMapLookup(as *ast.AssignStmt, call *ast.CallExpr, mapName string, valType types.Type) error {
	valC, err := goTypeToC(valType)
	if err != nil {
		return err
	}
	countIdent, ok := as.Lhs[0].(*ast.Ident)
	if !ok {
		return fmt.Errorf("%s: map lookup target must be an identifier", e.prog.FileSet.Position(as.Pos()))
	}
	okIdent, ok := as.Lhs[1].(*ast.Ident)
	if !ok {
		return fmt.Errorf("%s: map lookup ok target must be an identifier", e.prog.FileSet.Position(as.Pos()))
	}
	if len(call.Args) != 1 {
		return fmt.Errorf("%s: Lookup expects 1 argument", e.prog.FileSet.Position(call.Pos()))
	}
	keyExpr, err := e.formatExpr(call.Args[0])
	if err != nil {
		return err
	}
	e.writeIndent()
	e.writef("%s *%s = bpf_map_lookup_elem(&%s, %s);\n", valC, countIdent.Name, mapName, keyExpr)

	// Record alias: `ok` becomes the pointer's truthiness.
	if obj := e.prog.Info.Defs[okIdent]; obj != nil {
		e.aliases[obj] = countIdent.Name
	}
	return nil
}

// writeStorageGet emits the typed-pointer + ok-alias pair for a comma-ok
// storage Get, mirroring writeMapLookup. The kernel helper returns NULL
// when no entry exists; callers test ok by checking the pointer.
func (e *emitter) writeStorageGet(as *ast.AssignStmt, call *ast.CallExpr, mapName string, valType types.Type, helperFn string) error {
	valC, err := goTypeToC(valType)
	if err != nil {
		return err
	}
	valIdent, ok := as.Lhs[0].(*ast.Ident)
	if !ok {
		return fmt.Errorf("%s: storage Get target must be an identifier", e.prog.FileSet.Position(as.Pos()))
	}
	okIdent, ok := as.Lhs[1].(*ast.Ident)
	if !ok {
		return fmt.Errorf("%s: storage Get ok target must be an identifier", e.prog.FileSet.Position(as.Pos()))
	}
	if len(call.Args) != 1 {
		return fmt.Errorf("%s: Get expects 1 argument", e.prog.FileSet.Position(call.Pos()))
	}
	objExpr, err := e.formatExpr(call.Args[0])
	if err != nil {
		return err
	}
	e.writeIndent()
	e.writef("%s *%s = %s(&%s, %s, NULL, 0);\n", valC, valIdent.Name, helperFn, mapName, objExpr)
	if obj := e.prog.Info.Defs[okIdent]; obj != nil {
		e.aliases[obj] = valIdent.Name
	}
	return nil
}

func (e *emitter) writeIfStmt(is *ast.IfStmt) error {
	if is.Init != nil {
		return fmt.Errorf("%s: if-init clauses are not supported", e.prog.FileSet.Position(is.Pos()))
	}
	cond, err := e.formatExpr(is.Cond)
	if err != nil {
		return err
	}
	e.writeIndent()
	e.writef("if (%s) {\n", cond)
	e.indent++
	if err := e.writeBlock(is.Body); err != nil {
		return err
	}
	e.indent--
	e.writeIndent()
	if is.Else == nil {
		e.writeln("}")
		return nil
	}
	switch el := is.Else.(type) {
	case *ast.IfStmt:
		e.writef("} else ")
		// Emit the else-if inline: rewind by writing without leading indent.
		// We re-implement here to preserve `} else if (...)` formatting.
		condE, err := e.formatExpr(el.Cond)
		if err != nil {
			return err
		}
		e.writef("if (%s) {\n", condE)
		e.indent++
		if err := e.writeBlock(el.Body); err != nil {
			return err
		}
		e.indent--
		e.writeIndent()
		if el.Else != nil {
			// Recurse into the else chain.
			tail := &ast.IfStmt{Cond: el.Cond, Body: el.Body, Else: el.Else}
			_ = tail // noop; structure below handles it via simple else fallback
		}
		e.writeln("}")
	case *ast.BlockStmt:
		e.writef("} else {\n")
		e.indent++
		if err := e.writeBlock(el); err != nil {
			return err
		}
		e.indent--
		e.writeIndent()
		e.writeln("}")
	default:
		return fmt.Errorf("%s: unsupported else clause %T", e.prog.FileSet.Position(is.Pos()), is.Else)
	}
	return nil
}

func (e *emitter) writeReturnStmt(rs *ast.ReturnStmt) error {
	if len(rs.Results) == 0 {
		e.writeIndent()
		e.writeln("return;")
		return nil
	}
	if len(rs.Results) > 1 {
		return fmt.Errorf("%s: multi-value return not supported", e.prog.FileSet.Position(rs.Pos()))
	}
	val, err := e.formatExpr(rs.Results[0])
	if err != nil {
		return err
	}
	e.writeIndent()
	e.writef("return %s;\n", val)
	return nil
}

func (e *emitter) writeExprStmt(es *ast.ExprStmt) error {
	val, err := e.formatExpr(es.X)
	if err != nil {
		return err
	}
	e.writeIndent()
	e.writef("%s;\n", val)
	return nil
}

func (e *emitter) writeForStmt(fs *ast.ForStmt) error {
	// Only the constant-bounded form `for i := 0; i < N; i++` is supported.
	if fs.Init == nil || fs.Cond == nil || fs.Post == nil {
		return fmt.Errorf("%s: for loops must have init, condition, and post clauses", e.prog.FileSet.Position(fs.Pos()))
	}
	initStr, err := e.formatForClause(fs.Init)
	if err != nil {
		return err
	}
	condStr, err := e.formatExpr(fs.Cond)
	if err != nil {
		return err
	}
	postStr, err := e.formatForClause(fs.Post)
	if err != nil {
		return err
	}
	e.writeIndent()
	e.writef("for (%s; %s; %s) {\n", initStr, condStr, postStr)
	e.indent++
	if err := e.writeBlock(fs.Body); err != nil {
		return err
	}
	e.indent--
	e.writeIndent()
	e.writeln("}")
	return nil
}

func (e *emitter) formatForClause(stmt ast.Stmt) (string, error) {
	switch s := stmt.(type) {
	case *ast.AssignStmt:
		if len(s.Lhs) != 1 || len(s.Rhs) != 1 {
			return "", fmt.Errorf("%s: for clauses must be single assignment", e.prog.FileSet.Position(s.Pos()))
		}
		rhs, err := e.formatExpr(s.Rhs[0])
		if err != nil {
			return "", err
		}
		if s.Tok == token.DEFINE {
			id := s.Lhs[0].(*ast.Ident)
			t := e.prog.Info.TypeOf(id)
			cType, err := goTypeToC(t)
			if err != nil {
				return "", err
			}
			return fmt.Sprintf("%s = %s", declString(cType, id.Name), rhs), nil
		}
		lhs, err := e.formatExpr(s.Lhs[0])
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s %s %s", lhs, s.Tok.String(), rhs), nil
	case *ast.IncDecStmt:
		base, err := e.formatExpr(s.X)
		if err != nil {
			return "", err
		}
		if s.Tok == token.INC {
			return base + "++", nil
		}
		return base + "--", nil
	}
	return "", fmt.Errorf("%s: unsupported for clause %T", e.prog.FileSet.Position(stmt.Pos()), stmt)
}

// formatExpr returns the C representation of a Go expression as a string.
func (e *emitter) formatExpr(expr ast.Expr) (string, error) {
	switch x := expr.(type) {
	case *ast.BasicLit:
		return x.Value, nil
	case *ast.Ident:
		return e.formatIdent(x), nil
	case *ast.SelectorExpr:
		return e.formatSelector(x)
	case *ast.UnaryExpr:
		return e.formatUnary(x)
	case *ast.BinaryExpr:
		return e.formatBinary(x)
	case *ast.CallExpr:
		return e.formatCall(x)
	case *ast.ParenExpr:
		inner, err := e.formatExpr(x.X)
		if err != nil {
			return "", err
		}
		return "(" + inner + ")", nil
	case *ast.IndexExpr:
		base, err := e.formatExpr(x.X)
		if err != nil {
			return "", err
		}
		idx, err := e.formatExpr(x.Index)
		if err != nil {
			return "", err
		}
		return base + "[" + idx + "]", nil
	case *ast.StarExpr:
		inner, err := e.formatExpr(x.X)
		if err != nil {
			return "", err
		}
		return "*" + inner, nil
	}
	return "", fmt.Errorf("%s: unsupported expression %T", e.prog.FileSet.Position(expr.Pos()), expr)
}

func (e *emitter) formatIdent(id *ast.Ident) string {
	if obj, ok := e.prog.Info.Uses[id]; ok {
		if alias, has := e.aliases[obj]; has {
			return alias
		}
		// User-defined integer/string constants get inlined as literals.
		// bpf-package constants (XdpPass, TpOk, …) come through
		// formatSelector instead; this branch covers package-local consts.
		if c, isConst := obj.(*types.Const); isConst {
			if v := c.Val(); v != nil {
				return v.ExactString()
			}
		}
	}
	return id.Name
}

func (e *emitter) formatSelector(sel *ast.SelectorExpr) (string, error) {
	if pkgIdent, ok := sel.X.(*ast.Ident); ok {
		if obj := e.prog.Info.Uses[pkgIdent]; obj != nil {
			if pkgName, ok := obj.(*types.PkgName); ok && pkgName.Imported().Path() == bpfPkgPath {
				if c, ok := bpfConstants[sel.Sel.Name]; ok {
					return c, nil
				}
			}
		}
	}
	// Field access on a kernel-context pointer (e.g. `ctx.IngressIfIndex`)
	// becomes a CO-RE-relocated read at load time.
	if cChain, ok, err := e.coreReadChain(sel); err != nil {
		return "", err
	} else if ok {
		return cChain, nil
	}
	base, err := e.formatExpr(sel.X)
	if err != nil {
		return "", err
	}
	// Pointer receivers use C's arrow operator. Go autoderefs; C does not.
	// If the field carries a `bpf:"<c-name>"` tag, use that instead of the
	// Go field name.
	if t := e.prog.Info.TypeOf(sel.X); t != nil {
		if ptr, isPtr := t.(*types.Pointer); isPtr {
			fieldName := sel.Sel.Name
			if named, ok := ptr.Elem().(*types.Named); ok {
				if tag := bpfFieldNameTag(named, sel.Sel.Name); tag != "" {
					fieldName = tag
				}
			}
			return base + "->" + fieldName, nil
		}
	}
	return base + "." + sel.Sel.Name, nil
}

// bpfFieldNameTag returns the value of the `bpf:"…"` struct tag on
// goName-named field of named, or "" if no such tag exists.
func bpfFieldNameTag(named *types.Named, goName string) string {
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return ""
	}
	for i := 0; i < st.NumFields(); i++ {
		if st.Field(i).Name() != goName {
			continue
		}
		return parseBpfTag(st.Tag(i))
	}
	return ""
}

// coreReadChain detects field access on a `*bpf.<KernelStruct>` value and
// returns the equivalent BPF_CORE_READ(...) expression. Returns ok=false if
// the receiver isn't a kernel-context type.
//
// Single-level access:
//
//	ctx.IngressIfIndex            →  BPF_CORE_READ(ctx, ingress_ifindex)
//
// Chained access through multiple kernel structs:
//
//	task.Mm.Owner.Pid             →  BPF_CORE_READ(task, mm, owner, pid)
func (e *emitter) coreReadChain(sel *ast.SelectorExpr) (string, bool, error) {
	var fields []string
	cur := ast.Expr(sel)
	for {
		s, ok := cur.(*ast.SelectorExpr)
		if !ok {
			break
		}
		structType, ok := e.kernelStructType(s.X)
		if !ok {
			return "", false, nil
		}
		fieldName, ok := lookupKernelField(structType, s.Sel.Name)
		if !ok {
			return "", false, fmt.Errorf("%s: field %q not declared on kernel struct %s",
				e.prog.FileSet.Position(s.Pos()), s.Sel.Name, structType.Obj().Name())
		}
		fields = append([]string{fieldName}, fields...)
		cur = s.X
	}
	if len(fields) == 0 {
		return "", false, nil
	}
	base, err := e.formatExpr(cur)
	if err != nil {
		return "", false, err
	}
	parts := append([]string{base}, fields...)
	return "BPF_CORE_READ(" + strings.Join(parts, ", ") + ")", true, nil
}

// kernelStructType returns the underlying *types.Named for `*bpf.<Type>`
// expressions where <Type> is one of the kernel-context structs we model.
// Returns ok=false otherwise.
func (e *emitter) kernelStructType(x ast.Expr) (*types.Named, bool) {
	t := e.prog.Info.TypeOf(x)
	if t == nil {
		return nil, false
	}
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return nil, false
	}
	if !isKernelContextStruct(named) {
		return nil, false
	}
	return named, true
}

// isKernelContextStruct reports whether the named type is one of the
// bpf-package kernel-context structs whose field reads should go through
// BPF_CORE_READ.
func isKernelContextStruct(n *types.Named) bool {
	info, ok := bpfPackageTypeInfo(n)
	return ok && info.fieldsCORE
}

// lookupKernelField finds the C-side field name for a Go field on a kernel
// struct. Reads the `bpf:"..."` struct tag if present; falls back to a
// snake-cased version of the Go name.
func lookupKernelField(named *types.Named, goName string) (string, bool) {
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return "", false
	}
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		if f.Name() != goName {
			continue
		}
		if tagName := parseBpfTag(st.Tag(i)); tagName != "" {
			return tagName, true
		}
		return goCamelToSnake(goName), true
	}
	return "", false
}

func parseBpfTag(tag string) string {
	const key = `bpf:"`
	idx := strings.Index(tag, key)
	if idx < 0 {
		return ""
	}
	rest := tag[idx+len(key):]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return ""
	}
	return rest[:end]
}

func goCamelToSnake(s string) string {
	var b []byte
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b = append(b, '_')
		}
		if r >= 'A' && r <= 'Z' {
			r += 'a' - 'A'
		}
		b = append(b, byte(r))
	}
	return string(b)
}

func (e *emitter) formatUnary(u *ast.UnaryExpr) (string, error) {
	inner, err := e.formatExpr(u.X)
	if err != nil {
		return "", err
	}
	switch u.Op {
	case token.NOT:
		return "!" + inner, nil
	case token.AND:
		return "&" + inner, nil
	case token.SUB:
		return "-" + inner, nil
	case token.XOR:
		return "~" + inner, nil
	}
	return "", fmt.Errorf("%s: unsupported unary op %q", e.prog.FileSet.Position(u.Pos()), u.Op)
}

func (e *emitter) formatBinary(b *ast.BinaryExpr) (string, error) {
	l, err := e.formatExpr(b.X)
	if err != nil {
		return "", err
	}
	r, err := e.formatExpr(b.Y)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s %s %s", l, b.Op.String(), r), nil
}

// goBasicNameToC maps Go basic-type identifier names to their emitted C
// type. Used to detect and emit type conversions like `uint32(x)` → `(__u32)(x)`.
var goBasicNameToC = map[string]string{
	"bool":   "bool",
	"int8":   "__s8",
	"int16":  "__s16",
	"int32":  "__s32",
	"int64":  "__s64",
	"uint8":  "__u8",
	"uint16": "__u16",
	"uint32": "__u32",
	"uint64": "__u64",
}

// ringbufReserveCall returns (mapName, valType, true) if call is
// `<rb>.Reserve()` on a `*bpf.RingBuf[T]`.
func (e *emitter) ringbufReserveCall(call *ast.CallExpr) (string, types.Type, bool) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Reserve" {
		return "", nil, false
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", nil, false
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", nil, false
	}
	named, ok := t.(*types.Named)
	if !ok || !isRingBufNamed(named) {
		return "", nil, false
	}
	targs := named.TypeArgs()
	if targs == nil || targs.Len() != 1 {
		return "", nil, false
	}
	return id.Name, targs.At(0), true
}

func (e *emitter) writeRingbufReserve(as *ast.AssignStmt, mapName string, valType types.Type) error {
	valC, err := goTypeToC(valType)
	if err != nil {
		return err
	}
	eventIdent, ok := as.Lhs[0].(*ast.Ident)
	if !ok {
		return fmt.Errorf("%s: Reserve target must be an identifier", e.prog.FileSet.Position(as.Pos()))
	}
	okIdent, ok := as.Lhs[1].(*ast.Ident)
	if !ok {
		return fmt.Errorf("%s: Reserve ok target must be an identifier", e.prog.FileSet.Position(as.Pos()))
	}
	e.writeIndent()
	e.writef("%s *%s = bpf_ringbuf_reserve(&%s, sizeof(%s), 0);\n", valC, eventIdent.Name, mapName, valC)
	if obj := e.prog.Info.Defs[okIdent]; obj != nil {
		e.aliases[obj] = eventIdent.Name
	}
	return nil
}

// ringbufMethodCall recognizes `<rb>.{Submit,Discard,Output}(event)` on a
// `*bpf.RingBuf[T]`. Returns the C call string for the supported methods.
func (e *emitter) ringbufMethodCall(call *ast.CallExpr) (string, bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false, nil
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", false, nil
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", false, nil
	}
	named, ok := t.(*types.Named)
	if !ok || !isRingBufNamed(named) {
		return "", false, nil
	}
	if len(call.Args) != 1 {
		return "", false, fmt.Errorf("%s: %s expects exactly one argument", e.prog.FileSet.Position(call.Pos()), sel.Sel.Name)
	}
	arg, err := e.formatExpr(call.Args[0])
	if err != nil {
		return "", false, err
	}
	switch sel.Sel.Name {
	case "Submit":
		return fmt.Sprintf("bpf_ringbuf_submit(%s, 0)", arg), true, nil
	case "Discard":
		return fmt.Sprintf("bpf_ringbuf_discard(%s, 0)", arg), true, nil
	case "Output":
		return fmt.Sprintf("bpf_ringbuf_output(&%s, %s, sizeof(*%s), 0)", id.Name, arg, arg), true, nil
	}
	return "", false, nil
}

func isRingBufNamed(n *types.Named) bool {
	obj := n.Obj()
	if obj.Pkg() == nil || obj.Pkg().Path() != bpfPkgPath {
		return false
	}
	return obj.Name() == "RingBuf"
}

// queueLikeMethodCall recognises Push/Pop/Peek on a *bpf.Queue[T] or
// *bpf.Stack[T] and returns the matching libbpf helper call.
func (e *emitter) queueLikeMethodCall(call *ast.CallExpr) (string, bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false, nil
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", false, nil
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", false, nil
	}
	named, ok := t.(*types.Named)
	if !ok {
		return "", false, nil
	}
	if !isQueueOrStackNamed(named) {
		return "", false, nil
	}
	if len(call.Args) != 1 {
		return "", false, fmt.Errorf("%s: %s expects exactly one argument", e.prog.FileSet.Position(call.Pos()), sel.Sel.Name)
	}
	arg, err := e.formatExpr(call.Args[0])
	if err != nil {
		return "", false, err
	}
	switch sel.Sel.Name {
	case "Push":
		return fmt.Sprintf("bpf_map_push_elem(&%s, %s, 0)", id.Name, arg), true, nil
	case "Pop":
		return fmt.Sprintf("bpf_map_pop_elem(&%s, %s)", id.Name, arg), true, nil
	case "Peek":
		return fmt.Sprintf("bpf_map_peek_elem(&%s, %s)", id.Name, arg), true, nil
	}
	return "", false, nil
}

func isQueueOrStackNamed(n *types.Named) bool {
	obj := n.Obj()
	if obj.Pkg() == nil || obj.Pkg().Path() != bpfPkgPath {
		return false
	}
	return obj.Name() == "Queue" || obj.Name() == "Stack"
}

// progArrayMethodCall recognises (*bpf.ProgArray).TailCall(ctx, key).
func (e *emitter) progArrayMethodCall(call *ast.CallExpr) (string, bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "TailCall" {
		return "", false, nil
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", false, nil
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", false, nil
	}
	named, ok := t.(*types.Named)
	if !ok || named.Obj().Pkg() == nil ||
		named.Obj().Pkg().Path() != bpfPkgPath || named.Obj().Name() != "ProgArray" {
		return "", false, nil
	}
	if len(call.Args) != 2 {
		return "", false, fmt.Errorf("%s: TailCall expects (ctx, key)", e.prog.FileSet.Position(call.Pos()))
	}
	ctx, err := e.formatExpr(call.Args[0])
	if err != nil {
		return "", false, err
	}
	key, err := e.formatExpr(call.Args[1])
	if err != nil {
		return "", false, err
	}
	return fmt.Sprintf("bpf_tail_call(%s, &%s, %s)", ctx, id.Name, key), true, nil
}

// perfEventArrayMethodCall recognises (*bpf.PerfEventArray[T]).Output(ctx, val).
func (e *emitter) perfEventArrayMethodCall(call *ast.CallExpr) (string, bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Output" {
		return "", false, nil
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", false, nil
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", false, nil
	}
	named, ok := t.(*types.Named)
	if !ok || named.Obj().Pkg() == nil ||
		named.Obj().Pkg().Path() != bpfPkgPath || named.Obj().Name() != "PerfEventArray" {
		return "", false, nil
	}
	if len(call.Args) != 2 {
		return "", false, fmt.Errorf("%s: Output expects (ctx, *T)", e.prog.FileSet.Position(call.Pos()))
	}
	ctx, err := e.formatExpr(call.Args[0])
	if err != nil {
		return "", false, err
	}
	val, err := e.formatExpr(call.Args[1])
	if err != nil {
		return "", false, err
	}
	return fmt.Sprintf("bpf_perf_event_output(%s, &%s, BPF_F_CURRENT_CPU, %s, sizeof(*%s))", ctx, id.Name, val, val), true, nil
}

func (e *emitter) formatCall(call *ast.CallExpr) (string, error) {
	// Type conversion: T(x) where T is a Go basic type → (C-T)(x).
	if id, ok := call.Fun.(*ast.Ident); ok {
		if cType, isType := goBasicNameToC[id.Name]; isType {
			if len(call.Args) != 1 {
				return "", fmt.Errorf("%s: type conversion expects exactly one argument", e.prog.FileSet.Position(call.Pos()))
			}
			inner, err := e.formatExpr(call.Args[0])
			if err != nil {
				return "", err
			}
			return fmt.Sprintf("(%s)(%s)", cType, inner), nil
		}
	}

	// unsafe.Pointer(x) → x. C uses void* implicitly, so the cast is a no-op.
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Pointer" {
		if pkg, ok := sel.X.(*ast.Ident); ok && pkg.Name == "unsafe" {
			if len(call.Args) != 1 {
				return "", fmt.Errorf("%s: unsafe.Pointer expects exactly one argument", e.prog.FileSet.Position(call.Pos()))
			}
			return e.formatExpr(call.Args[0])
		}
	}

	// Ringbuf Submit / Discard / Output (Reserve is handled in writeAssignStmt's
	// comma-ok path).
	if c, ok, err := e.ringbufMethodCall(call); err != nil {
		return "", err
	} else if ok {
		return c, nil
	}

	// Queue / Stack: Push, Pop, Peek.
	if c, ok, err := e.queueLikeMethodCall(call); err != nil {
		return "", err
	} else if ok {
		return c, nil
	}

	// ProgArray.TailCall(ctx, key).
	if c, ok, err := e.progArrayMethodCall(call); err != nil {
		return "", err
	} else if ok {
		return c, nil
	}

	// PerfEventArray.Output(ctx, value).
	if c, ok, err := e.perfEventArrayMethodCall(call); err != nil {
		return "", err
	} else if ok {
		return c, nil
	}

	// TaskStorage / SkStorage / InodeStorage: Get, GetOrCreate, Delete.
	if c, ok, err := e.storageMethodCall(call); err != nil {
		return "", err
	} else if ok {
		return c, nil
	}

	// DevMap / CpuMap / XskMap: Redirect(ctx, key, flags). All three
	// share `bpf_redirect_map` and return XDP_REDIRECT or XDP_ABORTED.
	if c, ok, err := e.redirectMapCall(call); err != nil {
		return "", err
	} else if ok {
		return c, nil
	}

	// Map method calls: PktCount.Update(&k, &v), etc.
	if mapName, _, helper, isMap := e.mapMethodCall(call); isMap {
		args := []string{"&" + mapName}
		for _, a := range call.Args {
			s, err := e.formatExpr(a)
			if err != nil {
				return "", err
			}
			args = append(args, s)
		}
		if helper == "bpf_map_update_elem" {
			args = append(args, "BPF_ANY")
		}
		return fmt.Sprintf("%s(%s)", helper, strings.Join(args, ", ")), nil
	}

	// bpf.HelperFunc(args). Three resolution paths, in order:
	//   1. Sugar expansions: bpf.GetCurrentPid() etc. expand to specific
	//      C expressions instead of a one-to-one helper-name swap.
	//   2. Hand overrides: bpf.AtomicAdd64 → __sync_fetch_and_add.
	//   3. Auto-translation: bpf.MapLookupElem → bpf_map_lookup_elem.
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if pkgIdent, ok := sel.X.(*ast.Ident); ok {
			if obj := e.prog.Info.Uses[pkgIdent]; obj != nil {
				if pkgName, ok := obj.(*types.PkgName); ok && pkgName.Imported().Path() == bpfPkgPath {
					argStrs := make([]string, len(call.Args))
					for i, a := range call.Args {
						s, err := e.formatExpr(a)
						if err != nil {
							return "", err
						}
						argStrs[i] = s
					}
					if expand, ok := bpfHelperExpansions[sel.Sel.Name]; ok {
						return expand(argStrs)
					}
					cName, known := bpfHelperFuncs[sel.Sel.Name]
					if !known {
						cName = goNameToBpfHelper(sel.Sel.Name)
					}
					return fmt.Sprintf("%s(%s)", cName, strings.Join(argStrs, ", ")), nil
				}
			}
		}
	}

	// Fall-through: user function call.
	fn, err := e.formatExpr(call.Fun)
	if err != nil {
		return "", err
	}
	argStrs := make([]string, len(call.Args))
	for i, a := range call.Args {
		s, err := e.formatExpr(a)
		if err != nil {
			return "", err
		}
		argStrs[i] = s
	}
	return fmt.Sprintf("%s(%s)", fn, strings.Join(argStrs, ", ")), nil
}

// redirectMapCall handles Redirect(ctx, key, flags) on a DevMap, CpuMap,
// or XskMap. All three route to the single bpf_redirect_map helper; the
// userspace-controlled slot contents (ifindex / cpu / xsk fd) determine
// where the packet actually lands.
func (e *emitter) redirectMapCall(call *ast.CallExpr) (string, bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false, nil
	}
	if sel.Sel.Name != "Redirect" {
		return "", false, nil
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", false, nil
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", false, nil
	}
	if ptr, isPtr := t.(*types.Pointer); isPtr {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return "", false, nil
	}
	obj := named.Obj()
	if obj.Pkg() == nil || obj.Pkg().Path() != bpfPkgPath {
		return "", false, nil
	}
	if !redirectMapTypes[obj.Name()] {
		return "", false, nil
	}
	if len(call.Args) != 3 {
		return "", false, fmt.Errorf("%s: %s.Redirect expects (ctx, key, flags)", e.prog.FileSet.Position(call.Pos()), obj.Name())
	}
	// ctx is the program context pointer; it's unused by bpf_redirect_map
	// but we keep it in the Go signature so the call site reads
	// idiomatically alongside other ctx-taking helpers.
	keyExpr, err := e.formatExpr(call.Args[1])
	if err != nil {
		return "", false, err
	}
	flagsExpr, err := e.formatExpr(call.Args[2])
	if err != nil {
		return "", false, err
	}
	return fmt.Sprintf("bpf_redirect_map(&%s, %s, %s)", id.Name, keyExpr, flagsExpr), true, nil
}

// storageMapInfo extracts (mapName, valType, scopeKey) for a TaskStorage /
// SkStorage / InodeStorage method call. scopeKey is the storage Go type
// name ("TaskStorage" etc.) so the caller can look up the right helper.
// Returns ok=false if the call doesn't target a storage map.
func (e *emitter) storageMapInfo(sel *ast.SelectorExpr) (string, types.Type, string, bool) {
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", nil, "", false
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", nil, "", false
	}
	if ptr, isPtr := t.(*types.Pointer); isPtr {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return "", nil, "", false
	}
	obj := named.Obj()
	if obj.Pkg() == nil || obj.Pkg().Path() != bpfPkgPath {
		return "", nil, "", false
	}
	if _, isStorage := storageMapHelpers[obj.Name()]; !isStorage {
		return "", nil, "", false
	}
	targs := named.TypeArgs()
	if targs == nil || targs.Len() != 1 {
		return "", nil, "", false
	}
	return id.Name, targs.At(0), obj.Name(), true
}

// storageMethodCall handles TaskStorage / SkStorage / InodeStorage calls
// that aren't comma-ok Get (those are handled in writeAssignStmt). Covers
// GetOrCreate (returns *V) and Delete (returns int / error in Go terms).
func (e *emitter) storageMethodCall(call *ast.CallExpr) (string, bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false, nil
	}
	mapName, _, scope, ok := e.storageMapInfo(sel)
	if !ok {
		return "", false, nil
	}
	helpers := storageMapHelpers[scope]
	pos := e.prog.FileSet.Position(call.Pos())

	switch sel.Sel.Name {
	case "GetOrCreate":
		if len(call.Args) != 2 {
			return "", false, fmt.Errorf("%s: %s.GetOrCreate expects (obj, *V)", pos, scope)
		}
		objExpr, err := e.formatExpr(call.Args[0])
		if err != nil {
			return "", false, err
		}
		valExpr, err := e.formatExpr(call.Args[1])
		if err != nil {
			return "", false, err
		}
		return fmt.Sprintf("%s(&%s, %s, %s, BPF_LOCAL_STORAGE_GET_F_CREATE)", helpers.GetFn, mapName, objExpr, valExpr), true, nil
	case "Delete":
		if len(call.Args) != 1 {
			return "", false, fmt.Errorf("%s: %s.Delete expects (obj)", pos, scope)
		}
		objExpr, err := e.formatExpr(call.Args[0])
		if err != nil {
			return "", false, err
		}
		return fmt.Sprintf("%s(&%s, %s)", helpers.DeleteFn, mapName, objExpr), true, nil
	case "Get":
		// Standalone `taskCtx.Get(task)` (no comma-ok) renders as the raw
		// pointer expression. Comma-ok Get is handled in writeAssignStmt.
		if len(call.Args) != 1 {
			return "", false, fmt.Errorf("%s: %s.Get expects (obj)", pos, scope)
		}
		objExpr, err := e.formatExpr(call.Args[0])
		if err != nil {
			return "", false, err
		}
		return fmt.Sprintf("%s(&%s, %s, NULL, 0)", helpers.GetFn, mapName, objExpr), true, nil
	}
	return "", false, nil
}

// storageGetCall recognizes `<storage>.Get(obj)` for the comma-ok path
// (`v, ok := taskCtx.Get(task)`). Returns (mapName, valType, helperName)
// so the caller can emit the typed declaration with NULL-pointer fallback.
func (e *emitter) storageGetCall(call *ast.CallExpr) (string, types.Type, string, bool) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", nil, "", false
	}
	if sel.Sel.Name != "Get" {
		return "", nil, "", false
	}
	mapName, valType, scope, ok := e.storageMapInfo(sel)
	if !ok {
		return "", nil, "", false
	}
	return mapName, valType, storageMapHelpers[scope].GetFn, true
}

// mapLookupCall returns (mapName, valType, true) if call is `<mapVar>.Lookup(...)`
// where mapVar is a package-level bpf.ArrayMap or bpf.HashMap.
func (e *emitter) mapLookupCall(call *ast.CallExpr) (string, types.Type, bool) {
	mapName, valType, _, ok := e.mapMethodCall(call)
	if !ok {
		return "", nil, false
	}
	sel := call.Fun.(*ast.SelectorExpr)
	if sel.Sel.Name != "Lookup" {
		return "", nil, false
	}
	return mapName, valType, true
}

// mapMethodCall recognizes any `<mapVar>.<Method>(...)` call where mapVar is a
// gobee map type (ArrayMap or HashMap). Returns the map identifier name, its
// value type, the C helper name, and whether the call matches.
func (e *emitter) mapMethodCall(call *ast.CallExpr) (string, types.Type, string, bool) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", nil, "", false
	}
	helper, known := mapMethodToHelper[sel.Sel.Name]
	if !known {
		return "", nil, "", false
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", nil, "", false
	}
	t := e.prog.Info.TypeOf(sel.X)
	if t == nil {
		return "", nil, "", false
	}
	named, ok := t.(*types.Named)
	if !ok {
		return "", nil, "", false
	}
	if !isMapNamed(named) {
		return "", nil, "", false
	}
	targs := named.TypeArgs()
	if targs == nil || targs.Len() != 2 {
		return "", nil, "", false
	}
	return id.Name, targs.At(1), helper, true
}

func isMapNamed(n *types.Named) bool {
	obj := n.Obj()
	if obj.Pkg() == nil || obj.Pkg().Path() != bpfPkgPath {
		return false
	}
	return kernelMapGoTypes[obj.Name()]
}
